export const API_PATHS={
    AUTH:{
        REGISTER:"/auth/register",
        LOGIN:"/auth/login",
        GET_PROFILE:"/auth/profile",
        UPDATE_PROFILE="/auth/profile",
    },
    BOOKS:{
        CREATE_BOOK:"/books",
        GET_BOOKS:"/books",
        GET_BOOK_BY_ID:"/books",
        UPDATE_BOOK:"/books",
        DELETE_BOOK:"/books",
        UPDATE_COVER:"/books/cover",
    },
    AI:{
        GENERATE_OUTLINE:"/ai/generate-outline",
        GENERATE_CHAPTER_CONTENT:"/ai/generate-chapter-content",
    },
    EXPORT:{
        PDF:"/export",
        DOC:"/export",
    },
};